version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evaluation_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111
      POSTGRES_DB: contributor
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation_backend
    restart: always
    ports:
      - '3000:8000'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
